title: Blog
description: "Un pequeño blog para ir documentando mi progreso"
author:
  name: "Miguel Herraez"
  email: "migu.ds99@gmail.com"
  url: "http://miguelherrraez.github.io/miguelherraez"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "MiguelHerraez"
year : "2021"
